name: Upload Python Package
env:
  python_version: 3.8.12
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      -
        name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - test
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python_version }}
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    -
      name: Build package
      run: python -m build
    -
      name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
